### PR TITLE
Set up a "Hello world" project with two apps

### PR DESCRIPTION
**Pull request by joel-kalema**
Changes made in this pull request :
  - Setup React project
  - Setup linters
  - Added Greeting component

## [link to backend respository](https://github.com/joel-kalema/Hello-world-with-Webpack)

### CODE REVIEW

**Review by mahbubul14 — COMMENTED** [review]
# Invalid Code Review Request

**Hi @joel-kalema ,** 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

- [ ]  Currently, your `README` file is not updated according to the project. Please update your `README` file. You can use [this template ](https://github.com/microverseinc/readme-template)for the `README` but remember to customize it to your project.

- [ ] In the README file for the front end, you should provide a link to the Rails API (backend app).

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **Does not count** into the code reviews limit._
```

**Review by medaminedev66 — CHANGES_REQUESTED** [review]
Hi @joel-kalema , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request
- The README file for the backend does not have a link to the frontend repo. Please add a link to the frontend part in your README and request a new review.

You have submitted a project, that <EXPLAIN WHY PROJECT IS INVALID>

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by joel-kalema** [comment]
Hello @medaminedev66
Thank you for your feedback.
In this project, I installed the `Backend` and the `Frontend` in the same repo, that why there is no link to my `frontend`.

Annotation 2022-09-03 112654

**Review by alexander16108 — CHANGES_REQUESTED** [review]
Hi @joel-kalema , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

#### The README file for the backend does not have a link to the frontend repo. Please add a link to the frontend part in your README and request a new review.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by elisha2kyakpo1 — CHANGES_REQUESTED** [review]
Hi 👋 @joel-kalema, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

- The PR title and description looks professional✔️
- No linter errors ✔️
- You have a descriptive readme file✔️


## Required Changes ♻️
_Check the comments under the review._

- [ ] I haven't seen a react frontend app in order to complete the project requirements. Kindly add a frontend app link in the readme file or in the PR description.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
